# Generated by Django 5.1.3 on 2024-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('pub_year', models.PositiveSmallIntegerField(null=True, verbose_name='Publish date')),
            ],
        ),
    ]
