# Generated by Django 5.1.3 on 2024-11-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bp', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bp.boardgame')),
            ],
            options={
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
