# Generated by Django 5.1.3 on 2024-11-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bp', '0003_description_delete_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='Bp.boardgame'),
        ),
    ]
