# Generated by Django 5.1.3 on 2024-11-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bp', '0004_alter_description_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='pub_year',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='available_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='Bp.boardgame')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_borrowed'],
            },
        ),
    ]
