# Generated by Django 5.1.3 on 2024-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bp', '0005_remove_boardgame_pub_year_boardgame_available_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='pub_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Publication Year'),
        ),
    ]
