# Generated by Django 5.1.3 on 2024-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bp', '0006_boardgame_pub_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='total_copies',
            field=models.IntegerField(default=0),
        ),
    ]
